apiVersion: apps/v1
kind: Deployment
metadata:
 name: dotnet-app-deployment
 labels:
  app:autopilot-cluster-1
spec:
  replicas:3
selector:
   matchLabels:
    app:autopilot-cluster-1
template:
   metadata:
    labels:
     app:autopilot-cluster-1
   spec:
    containers:
     - name: autopilot-cluster-1
       image: utkarshgoyal/sampleKubernetes:latest
       ports:
        - name: http
        - containerPort: 80
        - protocol: TCP
---
 apiVersion: v1
 kind: Service
 metadata:
  name:autopilot-cluster-1
 spec:
    type: NodePort
    selector:
      app: autopilot-cluster-1
    ports:
      - protocol: TCP 
      - nodePort:30158
      - port:80
      - targetPort:80		