apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: autopilot-cluster-2
  template:
    metadata:
      labels:
        app: autopilot-cluster-2
    spec:
      containers:
      - name: autopilot-cluster-2
        image: utkarshgoyal/samplekubernetes:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: autopilot-cluster-2
spec:
  type: NodePort
  selector:
    app: autopilot-cluster-2
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30158