apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: autopilot-cluster-1
  template:
    metadata:
      labels:
        app: autopilot-cluster-1
    spec:
      containers:
      - name: autopilot-cluster-1
        image: utkarshgoyal/sampleKubernetes:latest
        ports:
        - containerPort: 80